version: '3'
services:
  web:
    environment:
      - VIRTUAL_HOST=wikijs.jamesgallagher.ie
    image: 91e862977f88
    ports:
      - "3000:3000"
      - "80"
    links:
      - mongodb
    network_mode: "bridge"
  mongodb:
    image: mongo
    network_mode: "bridge"
